apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: incident-management
  namespace: ocm-system
spec:
  interval: 1m0s
  component: github.com/sidhishruti22/ic-app
  version:
    semver: ">=v1.0.5"
  repository:
    url: incidents-mgmt-ocm.int.repositories.cloud.sap
    secretRef: 
      name: acreds
      