apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: incident-mgmt-deployment-test
  namespace: ocm-system
spec:
  interval: 1m0s
  sourceRef:
    kind: ComponentVersion
    name: incident-management-app
    resourceRef:
      name: deployment
      version: latest
