apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: incident-mgmt-deployment-test
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: incident-management
    namespace: ocm-system
  resource:
    name: ic-app-manifests
  snapshotTemplate:
    name: ic-app-deployment
